// Dataset fauna per il gioco di riconoscimento (nome -> specie -> famiglia).
// Generato dai documenti del corso; foto da Wikimedia Commons (ridimensionate).
export const FAUNA = [
  { common: "Aquila reale", sci: "Aquila chrysaetos", family: "Accipitridi", img: "fauna/aquila-reale.jpg" },
  { common: "Poiana", sci: "Buteo buteo", family: "Accipitridi", img: "fauna/poiana.jpg" },
  { common: "Allodola", sci: "Alauda arvensis", family: "Alaudidi", img: "fauna/allodola.jpg" },
  { common: "Cappellaccia", sci: "Galerida cristata", family: "Alaudidi", img: "fauna/cappellaccia.jpg" },
  { common: "Martin pescatore", sci: "Alcedo atthis", family: "Alcedinidi", img: "fauna/martin-pescatore.jpg" },
  { common: "Alzavola", sci: "Anas crecca", family: "Anatidi", img: "fauna/alzavola.jpg" },
  { common: "Canapiglia", sci: "Mareca strepera", family: "Anatidi", img: "fauna/canapiglia.jpg" },
  { common: "Cigno reale", sci: "Cygnus olor", family: "Anatidi", img: "fauna/cigno-reale.jpg" },
  { common: "Codone", sci: "Anas acuta", family: "Anatidi", img: "fauna/codone.jpg" },
  { common: "Fischione", sci: "Mareca penelope", family: "Anatidi", img: "fauna/fischione.jpg" },
  { common: "Fistione turco", sci: "Netta rufina", family: "Anatidi", img: "fauna/fistione-turco.jpg" },
  { common: "Germano reale", sci: "Anas platyrhynchos", family: "Anatidi", img: "fauna/germano-reale.jpg" },
  { common: "Marzaiola", sci: "Spatula querquedula", family: "Anatidi", img: "fauna/marzaiola.jpg" },
  { common: "Mestolone", sci: "Spatula clypeata", family: "Anatidi", img: "fauna/mestolone.jpg" },
  { common: "Moretta", sci: "Aythya fuligula", family: "Anatidi", img: "fauna/moretta.jpg" },
  { common: "Moretta tabaccata", sci: "Aythya nyroca", family: "Anatidi", img: "fauna/moretta-tabaccata.jpg" },
  { common: "Moriglione", sci: "Aythya ferina", family: "Anatidi", img: "fauna/moriglione.jpg" },
  { common: "Oca selvatica", sci: "Anser anser", family: "Anatidi", img: "fauna/oca-selvatica.jpg" },
  { common: "Smergo maggiore", sci: "Mergus merganser", family: "Anatidi", img: "fauna/smergo-maggiore.jpg" },
  { common: "Volpoca", sci: "Tadorna tadorna", family: "Anatidi", img: "fauna/volpoca.jpg" },
  { common: "Rondone comune", sci: "Apus apus", family: "Apodidi", img: "fauna/rondone-comune.jpg" },
  { common: "Airone bianco maggiore", sci: "Ardea alba", family: "Ardeidi", img: "fauna/airone-bianco-maggiore.jpg" },
  { common: "Airone cenerino", sci: "Ardea cinerea", family: "Ardeidi", img: "fauna/airone-cenerino.jpg" },
  { common: "Garzetta", sci: "Egretta garzetta", family: "Ardeidi", img: "fauna/garzetta.jpg" },
  { common: "Nitticora", sci: "Nycticorax nycticorax", family: "Ardeidi", img: "fauna/nitticora.jpg" },
  { common: "Tarabuso", sci: "Botaurus stellaris", family: "Ardeidi", img: "fauna/tarabuso.jpg" },
  { common: "Camoscio alpino", sci: "Rupicapra rupicapra", family: "Bovidi", img: "fauna/camoscio-alpino.jpg" },
  { common: "Muflone", sci: "Ovis aries musimon", family: "Bovidi", img: "fauna/muflone.jpg" },
  { common: "Stambecco", sci: "Capra ibex", family: "Bovidi", img: "fauna/stambecco.jpg" },
  { common: "Occhione", sci: "Burhinus oedicnemus", family: "Burinidi", img: "fauna/occhione.jpg" },
  { common: "Lupo", sci: "Canis lupus", family: "Canidi", img: "fauna/lupo.jpg" },
  { common: "Volpe", sci: "Vulpes vulpes", family: "Canidi", img: "fauna/volpe.jpg" },
  { common: "Succiacapre", sci: "Caprimulgus europaeus", family: "Caprimulgidi", img: "fauna/succiacapre.jpg" },
  { common: "Pavoncella", sci: "Vanellus vanellus", family: "Caradridi", img: "fauna/pavoncella.jpg" },
  { common: "Piviere dorato", sci: "Pluvialis apricaria", family: "Caradridi", img: "fauna/piviere-dorato.jpg" },
  { common: "Capriolo", sci: "Capreolus capreolus", family: "Cervidi", img: "fauna/capriolo.jpg" },
  { common: "Cervo", sci: "Cervus elaphus", family: "Cervidi", img: "fauna/cervo.jpg" },
  { common: "Daino", sci: "Dama dama", family: "Cervidi", img: "fauna/daino.jpg" },
  { common: "Cicogna bianca", sci: "Ciconia ciconia", family: "Ciconiidi", img: "fauna/cicogna-bianca.jpg" },
  { common: "Merlo acquaiolo", sci: "Cinclus cinclus", family: "Cinclidi", img: "fauna/merlo-acquaiolo.jpg" },
  { common: "Colombaccio", sci: "Columba palumbus", family: "Columbidi", img: "fauna/colombaccio.jpg" },
  { common: "Colombella", sci: "Columba oenas", family: "Columbidi", img: "fauna/colombella.jpg" },
  { common: "Piccione", sci: "Columba livia", family: "Columbidi", img: "fauna/piccione.jpg" },
  { common: "Tortora dal collare", sci: "Streptopelia decaocto", family: "Columbidi", img: "fauna/tortora-dal-collare.jpg" },
  { common: "Tortora selvatica", sci: "Streptopelia turtur", family: "Columbidi", img: "fauna/tortora-selvatica.jpg" },
  { common: "Cornacchia grigia", sci: "Corvus cornix", family: "Corvidi", img: "fauna/cornacchia-grigia.jpg" },
  { common: "Cornacchia nera", sci: "Corvus corone", family: "Corvidi", img: "fauna/cornacchia-nera.jpg" },
  { common: "Corvo imperiale", sci: "Corvus corax", family: "Corvidi", img: "fauna/corvo-imperiale.jpg" },
  { common: "Gazza", sci: "Pica pica", family: "Corvidi", img: "fauna/gazza.jpg" },
  { common: "Ghiandaia", sci: "Garrulus glandarius", family: "Corvidi", img: "fauna/ghiandaia.jpg" },
  { common: "Taccola", sci: "Coloeus monedula", family: "Corvidi", img: "fauna/taccola.jpg" },
  { common: "Cuculo", sci: "Cuculus canorus", family: "Cuculidi", img: "fauna/cuculo.jpg" },
  { common: "Cormorano", sci: "Phalacrocorax carbo", family: "Falacrocoracidi", img: "fauna/cormorano.jpg" },
  { common: "Falco pellegrino", sci: "Falco peregrinus", family: "Falconidi", img: "fauna/falco-pellegrino.jpg" },
  { common: "Gheppio", sci: "Falco tinnunculus", family: "Falconidi", img: "fauna/gheppio.jpg" },
  { common: "Coturnice", sci: "Alectoris graeca", family: "Fasianidi", img: "fauna/coturnice.jpg" },
  { common: "Fagiano comune", sci: "Phasianus colchicus", family: "Fasianidi", img: "fauna/fagiano-comune.jpg" },
  { common: "Pernice rossa", sci: "Alectoris rufa", family: "Fasianidi", img: "fauna/pernice-rossa.jpg" },
  { common: "Quaglia", sci: "Coturnix coturnix", family: "Fasianidi", img: "fauna/quaglia.jpg" },
  { common: "Starna", sci: "Perdix perdix", family: "Fasianidi", img: "fauna/starna.jpg" },
  { common: "Gatto selvatico", sci: "Felis silvestris", family: "Felidi", img: "fauna/gatto-selvatico.jpg" },
  { common: "Cardellino", sci: "Carduelis carduelis", family: "Fringillidi", img: "fauna/cardellino.jpg" },
  { common: "Fringuello", sci: "Fringilla coelebs", family: "Fringillidi", img: "fauna/fringuello.jpg" },
  { common: "Frosone", sci: "Coccothraustes coccothraustes", family: "Fringillidi", img: "fauna/frosone.jpg" },
  { common: "Peppola", sci: "Fringilla montifringilla", family: "Fringillidi", img: "fauna/peppola.jpg" },
  { common: "Verdone", sci: "Chloris chloris", family: "Fringillidi", img: "fauna/verdone.jpg" },
  { common: "Istrice", sci: "Hystrix cristata", family: "Istricidi", img: "fauna/istrice.jpg" },
  { common: "Gabbiano reale", sci: "Larus michahellis", family: "Laridi", img: "fauna/gabbiano-reale.jpg" },
  { common: "Coniglio selvatico", sci: "Oryctolagus cuniculus", family: "Leporidi", img: "fauna/coniglio-selvatico.jpg" },
  { common: "Lepre bianca", sci: "Lepus timidus", family: "Leporidi", img: "fauna/lepre-bianca.jpg" },
  { common: "Lepre comune", sci: "Lepus europaeus", family: "Leporidi", img: "fauna/lepre-comune.jpg" },
  { common: "Silvilago", sci: "Sylvilagus floridanus", family: "Leporidi", img: "fauna/silvilago.jpg" },
  { common: "Gruccione", sci: "Merops apiaster", family: "Meropidi", img: "fauna/gruccione.jpg" },
  { common: "Nutria", sci: "Myocastor coypus", family: "Miocastoridi", img: "fauna/nutria.jpg" },
  { common: "Ballerina bianca", sci: "Motacilla alba", family: "Motacillidi", img: "fauna/ballerina-bianca.jpg" },
  { common: "Pispola", sci: "Anthus pratensis", family: "Motacillidi", img: "fauna/pispola.jpg" },
  { common: "Codirosso", sci: "Phoenicurus phoenicurus", family: "Muscicapidi", img: "fauna/codirosso.jpg" },
  { common: "Pettirosso", sci: "Erithacus rubecula", family: "Muscicapidi", img: "fauna/pettirosso.jpg" },
  { common: "Donnola", sci: "Mustela nivalis", family: "Mustelidi", img: "fauna/donnola.jpg" },
  { common: "Faina", sci: "Martes foina", family: "Mustelidi", img: "fauna/faina.jpg" },
  { common: "Martora", sci: "Martes martes", family: "Mustelidi", img: "fauna/martora.jpg" },
  { common: "Tasso", sci: "Meles meles", family: "Mustelidi", img: "fauna/tasso.jpg" },
  { common: "Cinciallegra", sci: "Parus major", family: "Paridi", img: "fauna/cinciallegra.jpg" },
  { common: "Passera d'Italia", sci: "Passer italiae", family: "Passeridi", img: "fauna/passera-d-italia.jpg" },
  { common: "Passera mattugia", sci: "Passer montanus", family: "Passeridi", img: "fauna/passera-mattugia.jpg" },
  { common: "Picchio verde", sci: "Picus viridis", family: "Picidi", img: "fauna/picchio-verde.jpg" },
  { common: "Svasso maggiore", sci: "Podiceps cristatus", family: "Podicipedidi", img: "fauna/svasso-maggiore.jpg" },
  { common: "Folaga", sci: "Fulica atra", family: "Rallidi", img: "fauna/folaga.jpg" },
  { common: "Gallinella d'acqua", sci: "Gallinula chloropus", family: "Rallidi", img: "fauna/gallinella-d-acqua.jpg" },
  { common: "Porciglione", sci: "Rallus aquaticus", family: "Rallidi", img: "fauna/porciglione.jpg" },
  { common: "Avocetta", sci: "Recurvirostra avosetta", family: "Recurvirostridi", img: "fauna/avocetta.jpg" },
  { common: "Cavaliere d'Italia", sci: "Himantopus himantopus", family: "Recurvirostridi", img: "fauna/cavaliere-d-italia.jpg" },
  { common: "Beccaccia", sci: "Scolopax rusticola", family: "Scolopacidi", img: "fauna/beccaccia.jpg" },
  { common: "Beccaccino", sci: "Gallinago gallinago", family: "Scolopacidi", img: "fauna/beccaccino.jpg" },
  { common: "Combattente", sci: "Calidris pugnax", family: "Scolopacidi", img: "fauna/combattente.jpg" },
  { common: "Frullino", sci: "Lymnocryptes minimus", family: "Scolopacidi", img: "fauna/frullino.jpg" },
  { common: "Pittima reale", sci: "Limosa limosa", family: "Scolopacidi", img: "fauna/pittima-reale.jpg" },
  { common: "Picchio muratore", sci: "Sitta europaea", family: "Sittidi", img: "fauna/picchio-muratore.jpg" },
  { common: "Allocco", sci: "Strix aluco", family: "Strigidi", img: "fauna/allocco.jpg" },
  { common: "Civetta", sci: "Athene noctua", family: "Strigidi", img: "fauna/civetta.jpg" },
  { common: "Gufo comune", sci: "Asio otus", family: "Strigidi", img: "fauna/gufo-comune.jpg" },
  { common: "Storno", sci: "Sturnus vulgaris", family: "Sturnidi", img: "fauna/storno.jpg" },
  { common: "Cinghiale", sci: "Sus scrofa", family: "Suidi", img: "fauna/cinghiale.jpg" },
  { common: "Fagiano di monte", sci: "Lyrurus tetrix", family: "Tetraonidi", img: "fauna/fagiano-di-monte.jpg" },
  { common: "Francolino di monte", sci: "Tetrastes bonasia", family: "Tetraonidi", img: "fauna/francolino-di-monte.jpg" },
  { common: "Gallo cedrone", sci: "Tetrao urogallus", family: "Tetraonidi", img: "fauna/gallo-cedrone.jpg" },
  { common: "Pernice bianca", sci: "Lagopus muta", family: "Tetraonidi", img: "fauna/pernice-bianca.jpg" },
  { common: "Barbagianni", sci: "Tyto alba", family: "Titonidi", img: "fauna/barbagianni.jpg" },
  { common: "Cesena", sci: "Turdus pilaris", family: "Turdidi", img: "fauna/cesena.jpg" },
  { common: "Merlo", sci: "Turdus merula", family: "Turdidi", img: "fauna/merlo.jpg" },
  { common: "Tordela", sci: "Turdus viscivorus", family: "Turdidi", img: "fauna/tordela.jpg" },
  { common: "Tordo bottaccio", sci: "Turdus philomelos", family: "Turdidi", img: "fauna/tordo-bottaccio.jpg" },
  { common: "Tordo sassello", sci: "Turdus iliacus", family: "Turdidi", img: "fauna/tordo-sassello.jpg" },
  { common: "Upupa", sci: "Upupa epops", family: "Upupidi", img: "fauna/upupa.jpg" },
];
